slug = "catppuccin-mocha"
name = "Catppuccin Mocha"
creator = "Catppuccin Org"
description = "Soothing pastel theme for Revolt."
tags = ["pastel", "soothing", "dark"]
version = "2.0.0"

[variables]
light = false
accent = "#cba6f7"
background = "#1e1e2e"
foreground = "#cdd6f4"
block = "#11111b"
message-box = "#11111b"
mention = "rgba(30, 30, 46, 0.10)"
success = "#a6e3a1"
warning = "#fab387"
tooltip = "#000000"
error = "#f38ba8"
hover = "rgba(17, 17, 27, 0.75)"

[variables.scrollbar]
thumb = "#b4befe"
track = "transparent"

[variables.primary]
background = "#1e1e2e"
header = "#181825"

[variables.secondary]
background = "#181825"
foreground = "#6c7086"
header = "#181825"

[variables.tertiary]
background = "#11111b"
foreground = "#585b70"

[variables.status]
online = "#a6e3a1"
away = "#f9e2af"
focus = "#89b4fa"
busy = "#f38ba8"
streaming = "#cba6f7"
invisible = "#585b70"
