slug = "catppuccin"
name = "Catppuccin"
creator = "Andreas Grafen"
description = "Dark theme using primer color primatives."
tags = ["pastel", "soothing"]
version = "1.0.0"

[variables]
light = false
accent = "#C9CBFF"
background = "#1E1E2E"
foreground = "#C9CBFF"
block = "#161320"
message-box = "#161320"
mention = "rgba(201, 203, 255, .1)"
success = "#ABE9B3"
warning = "#F8BD96"
error = "#F28FAD"
hover = "rgba(22, 19, 32, .75)"

[variables.scrollbar]
thumb = "#C9CBFF"
track = "transparent"

[variables.primary]
background = "#1E1E2E"
header = "#1A1826"

[variables.secondary]
background = "#1A1826"
foreground = "#988BA2"
header = "#1A1826"

[variables.tertiary]
background = "#161320"
foreground = "#6E6C7E"

[variables.status]
online = "#ABE9B3"
away = "#F2CDCD"
busy = "#E8A2AF"
streaming = "#DDB6F2"
invisible = "#6E6C7E"
